name: Scheduled Webhook Sender

on:
  schedule:
    # Runs every 5 minutes
    - cron: '*/5 * * * *'

jobs:
  send_webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Webhook
        run: |
          WEBHOOK_URL="https://discord.com/api/webhooks/1379038305831620638/NBIvFrPcOJ2wcCCnNjNg2H8HbCl-WKC21z6Hav44kuTGvatklsci2hwT2NUejT6XSwoG"
          CURRENT_TIME=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          TARGET_DATE="2025-12-02T09:27:00Z"
          START_DATE="2025-06-02T09:27:00Z"

          # Calculate time differences in seconds
          CURRENT_EPOCH=$(date -d "$CURRENT_TIME" +%s)
          TARGET_EPOCH=$(date -d "$TARGET_DATE" +%s)
          START_EPOCH=$(date -d "$START_DATE" +%s)

          REMAINING_SECONDS=$((TARGET_EPOCH - CURRENT_EPOCH))
          ELAPSED_SECONDS=$((CURRENT_EPOCH - START_EPOCH))
          TOTAL_SECONDS=$((TARGET_EPOCH - START_EPOCH))

          if [ $REMAINING_SECONDS -le 0 ]; then
            TIME_REMAINING="0d 0h 0m 0s"
            PROGRESS_PERCENT=100
          else
            DAYS=$((REMAINING_SECONDS / 86400))
            HOURS=$(((REMAINING_SECONDS % 86400) / 3600))
            MINUTES=$(((REMAINING_SECONDS % 3600) / 60))
            SECONDS=$((REMAINING_SECONDS % 60))
            TIME_REMAINING="${DAYS}d ${HOURS}h ${MINUTES}m ${SECONDS}s"

            PROGRESS_PERCENT=$((ELAPSED_SECONDS * 100 / TOTAL_SECONDS))
          fi

          # Build progress bar
          BAR_LENGTH=20
          FILLED_LENGTH=$((BAR_LENGTH * PROGRESS_PERCENT / 100))
          EMPTY_LENGTH=$((BAR_LENGTH - FILLED_LENGTH))
          PROGRESS_BAR=$(printf '🟥%.0s' $(seq 1 $FILLED_LENGTH))
          PROGRESS_BAR+=$(printf '⬜%.0s' $(seq 1 $EMPTY_LENGTH))

          # Build JSON payload
          read -r -d '' PAYLOAD << EOM
{
  "embeds": [
    {
      "title": "🚀 Henclin Unban Countdown 🚀",
      "description": "Scheduled webhook from GitHub Actions",
      "color": 14804227,
      "fields": [
        {
          "name": "Time Remaining",
          "value": "$TIME_REMAINING",
          "inline": true
        },
        {
          "name": "Progress",
          "value": "$PROGRESS_BAR",
          "inline": true
        },
        {
          "name": "Percentage Complete",
          "value": "$PROGRESS_PERCENT%",
          "inline": true
        }
      ],
      "footer": {
        "text": "Henclin Unban Countdown",
        "icon_url": "https://cdn-icons-png.flaticon.com/512/2920/2920250.png"
      },
      "timestamp": "$CURRENT_TIME"
    }
  ]
}
EOM

          curl -H "Content-Type: application/json" -X POST -d "$PAYLOAD" "$WEBHOOK_URL"
