name: Discord Countdown Bot

on:
  schedule:
    - cron: '*/5 * * * *'  # Update setiap 5 menit (lebih aman)

jobs:
  send-countdown:
    runs-on: ubuntu-latest
    steps:
      - name: Hitung dan kirim countdown
        env:
          WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          # Konfigurasi waktu
          TARGET="2025-12-02T09:27:00Z"
          NOW=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          
          # Hitung detik
          target_sec=$(date -d "$TARGET" +%s)
          now_sec=$(date -d "$NOW" +%s)
          remaining=$((target_sec - now_sec))

          # Format waktu
          days=$((remaining / 86400))
          hours=$(( (remaining % 86400) / 3600 ))
          mins=$(( (remaining % 3600) / 60 ))
          secs=$((remaining % 60))

          # Buat payload
          payload='{
            "embeds": [{
              "title": "⏳ COUNTDOWN BOT ⏳",
              "description": "Waktu tersisa: '"${days}d ${hours}h ${mins}m ${secs}s"'",
              "color": 5814783,
              "footer": {"text": "Update: '"$NOW"'"}
            }]
          }'

          # Kirim ke Discord
          curl -s -X POST -H "Content-Type: application/json" -d "$payload" "$WEBHOOK_URL"
