name: Discord Countdown Bot

on:
  schedule:
    - cron: '*/5 * * * *'  # Update setiap 5 menit (aman untuk rate limit)
  workflow_dispatch:  # Memungkinkan trigger manual

jobs:
  countdown:
    runs-on: ubuntu-latest
    steps:
      - name: Setup countdown
        id: countdown
        env:
          TARGET_DATE: "2025-12-02T09:27:00Z"  # Ganti dengan tanggal target Anda
          START_DATE: "2025-06-02T09:27:00Z"   # Ganti dengan tanggal mulai
        run: |
          # Hitung waktu
          NOW=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          target_sec=$(date -d "$TARGET_DATE" +%s)
          start_sec=$(date -d "$START_DATE" +%s)
          now_sec=$(date -d "$NOW" +%s)

          # Kalkulasi
          remaining=$((target_sec - now_sec))
          elapsed=$((now_sec - start_sec))
          total=$((target_sec - start_sec))

          # Format waktu
          days=$((remaining / 86400))
          hours=$(( (remaining % 86400) / 3600 ))
          mins=$(( (remaining % 3600) / 60 ))
          secs=$((remaining % 60))
          percent=$(( (elapsed * 100) / total ))

          # Progress bar
          bar=$(printf '🟥%.0s' $(seq 1 $((percent/5))))$(printf '⬜%.0s' $(seq 1 $((20-(percent/5))))

          # Status message
          if [ $percent -ge 100 ]; then
            status="🎉 COUNTDOWN SELESAI! 🎉"
          elif [ $percent -gt 75 ]; then
            status="Hampir selesai!"
          else
            status="Berjalan..."
          fi

          # Simpan output untuk step berikutnya
          echo "percent=${percent}" >> $GITHUB_OUTPUT
          echo "status=${status}" >> $GITHUB_OUTPUT
          echo "time=${days}d ${hours}h ${mins}m ${secs}s" >> $GITHUB_OUTPUT
          echo "bar=${bar}" >> $GITHUB_OUTPUT
          echo "now=${NOW}" >> $GITHUB_OUTPUT

      - name: Send to Discord
        if: always()  # Tetap jalankan meski step sebelumnya error
        env:
          WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          payload='{
            "embeds": [{
              "title": "⏳ COUNTDOWN BOT",
              "description": "**${{ steps.countdown.outputs.status }}**\n\n${{ steps.countdown.outputs.time }}",
              "color": 16776960,
              "fields": [
                {"name": "Progress", "value": "${{ steps.countdown.outputs.bar }} ${{ steps.countdown.outputs.percent }}%", "inline": false}
              ],
              "footer": {"text": "Update: ${{ steps.countdown.outputs.now }}"}
            }]
          }'

          # Kirim dengan error handling
          response=$(curl -s -o /dev/null -w "%{http_code}" -X POST \
            -H "Content-Type: application/json" \
            -d "$payload" \
            "$WEBHOOK_URL")

          if [ "$response" -ne 204 ]; then
            echo "Error: Failed to send webhook (HTTP $response)"
            exit 1
          fi
