name: Discord Countdown Bot

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:       # Allows manual triggering

jobs:
  countdown:
    runs-on: ubuntu-latest
    steps:
      - name: Calculate time remaining
        id: timer
        run: |
          # Set your target date (ISO 8601 format)
          TARGET="2025-12-02T09:27:00Z"
          NOW=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

          # Calculate seconds
          target_sec=$(date -d "$TARGET" +%s)
          now_sec=$(date -d "$NOW" +%s)
          remaining=$((target_sec - now_sec))

          # Format time components
          days=$((remaining / 86400))
          hours=$(( (remaining % 86400) / 3600 ))
          mins=$(( (remaining % 3600) / 60 ))
          secs=$((remaining % 60))

          # Calculate percentage (simplified)
          total_days=$(( (target_sec - $(date -d "2025-06-02T09:27:00Z" +%s)) / 86400 ))
          elapsed_days=$(( (now_sec - $(date -d "2025-06-02T09:27:00Z" +%s)) / 86400 ))
          percent=$(( (elapsed_days * 100) / total_days ))

          # Create progress bar
          bar_length=20
          filled=$(( percent * bar_length / 100 ))
          progress_bar=$(printf '🟩%.0s' $(seq 1 $filled))$(printf '⬜%.0s' $(seq 1 $((bar_length - filled))))

          # Output results
          echo "time_remaining=${days}d ${hours}h ${mins}m ${secs}s" >> $GITHUB_OUTPUT
          echo "progress=${progress_bar} ${percent}%" >> $GITHUB_OUTPUT
          echo "current_time=${NOW}" >> $GITHUB_OUTPUT

      - name: Send to Discord
        env:
          WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          payload='{
            "embeds": [{
              "title": "⏳ Unban Countdown",
              "description": "**Time remaining:** ${{ steps.timer.outputs.time_remaining }}",
              "color": 65280,
              "fields": [
                {
                  "name": "Progress",
                  "value": "${{ steps.timer.outputs.progress }}",
                  "inline": false
                }
              ],
              "footer": {
                "text": "Last updated: ${{ steps.timer.outputs.current_time }}"
              }
            }]
          }'

          # Send with error handling
          curl_response=$(curl -s -o /dev/null -w "%{http_code}" \
            -X POST \
            -H "Content-Type: application/json" \
            -d "$payload" \
            "$WEBHOOK_URL")

          if [ "$curl_response" -ne 204 ]; then
            echo "Error: Discord webhook failed (HTTP $curl_response)"
            exit 1
          fi
