name: Scheduled Webhook Sender

on:
  schedule:
    - cron: '*/5 * * * *'  # Every 5 minutes
  workflow_dispatch:

jobs:
  send_webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq curl

      - name: Send Discord Webhook
        env:
          WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        shell: bash
        run: |
          # Set timezone and get current time
          export TZ=UTC
          CURRENT_TIME=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          TARGET_DATE="2025-12-02T09:27:00Z"
          START_DATE="2025-06-02T09:27:00Z"

          # Calculate time differences
          CURRENT_EPOCH=$(date -d "$CURRENT_TIME" +%s)
          TARGET_EPOCH=$(date -d "$TARGET_DATE" +%s)
          START_EPOCH=$(date -d "$START_DATE" +%s)

          REMAINING_SECONDS=$((TARGET_EPOCH - CURRENT_EPOCH))
          ELAPSED_SECONDS=$((CURRENT_EPOCH - START_EPOCH))
          TOTAL_SECONDS=$((TARGET_EPOCH - START_EPOCH))

          # Calculate remaining time
          if [ $REMAINING_SECONDS -le 0 ]; then
            TIME_REMAINING="0d 0h 0m 0s"
            PROGRESS_PERCENT=100
          else
            DAYS=$((REMAINING_SECONDS / 86400))
            HOURS=$(((REMAINING_SECONDS % 86400) / 3600))
            MINUTES=$(((REMAINING_SECONDS % 3600) / 60))
            SECONDS=$((REMAINING_SECONDS % 60))
            TIME_REMAINING="${DAYS}d ${HOURS}h ${MINUTES}m ${SECONDS}s"
            PROGRESS_PERCENT=$((ELAPSED_SECONDS * 100 / TOTAL_SECONDS))
            [ $PROGRESS_PERCENT -gt 100 ] && PROGRESS_PERCENT=100
          fi

          # Build progress bar
          BAR_LENGTH=20
          FILLED_LENGTH=$((BAR_LENGTH * PROGRESS_PERCENT / 100))
          EMPTY_LENGTH=$((BAR_LENGTH - FILLED_LENGTH))
          PROGRESS_BAR="[$(printf '🟥%.0s' $(seq 1 $FILLED_LENGTH))$(printf '⬜%.0s' $(seq 1 $EMPTY_LENGTH))]"

          # Build and send payload
          PAYLOAD=$(jq -n \
            --arg tr "$TIME_REMAINING" \
            --arg pb "$PROGRESS_BAR" \
            --arg pp "$PROGRESS_PERCENT" \
            --arg ct "$CURRENT_TIME" \
            '{
              "embeds": [{
                "title": "🚀 Henclin Unban Countdown 🚀",
                "description": "Time until Henclin is unbanned",
                "color": 14804227,
                "fields": [
                  {
                    "name": "Time Remaining",
                    "value": $tr,
                    "inline": true
                  },
                  {
                    "name": "Progress",
                    "value": $pb,
                    "inline": true
                  },
                  {
                    "name": "Percentage Complete",
                    "value": ($pp + "%"),
                    "inline": true
                  }
                ],
                "footer": {
                  "text": "Henclin Unban Countdown",
                  "icon_url": "https://cdn-icons-png.flaticon.com/512/2920/2920250.png"
                },
                "timestamp": $ct
              }]
            }')

          # Send with error handling
          echo "Sending webhook..."
          curl_response=$(curl -s -o /dev/null -w "%{http_code}" \
            -H "Content-Type: application/json" \
            -X POST \
            -d "$PAYLOAD" \
            "$WEBHOOK_URL")

          if [ "$curl_response" = "204" ]; then
            echo "Webhook sent successfully!"
          else
            echo "⚠️ Failed to send webhook (HTTP $curl_response)"
            echo "Payload: $PAYLOAD"
            exit 1
          fi
