name: Send Discord Webhook
on:
  schedule:
    # Runs every 60 minutes
    - cron: '*/5 * * * *'
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  send-webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Versi LTS terbaru
          cache: 'npm'
          
      - name: Install dependencies
        run: |
          npm install
          npm ci --omit=dev
          
      - name: Verify Node.js installation
        run: |
          node -v
          npm -v
          
      - name: Send webhook
        run: npm start
        env:
          NODE_OPTIONS: '--no-warnings'
