name: Discord Countdown Bot

on:
  schedule:
    - cron: '*/5 * * * *'  # Update setiap 5 menit

jobs:
  send-countdown:
    runs-on: ubuntu-latest
    steps:
      - name: Hitung dan kirim countdown
        env:
          WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          # Atur tanggal target dan mulai
          TARGET="2025-12-02T09:27:00Z"  # Ganti dengan tanggal target Anda
          START="2025-06-02T09:27:00Z"   # Ganti dengan tanggal mulai
          NOW=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

          # Hitung waktu dalam detik
          target_sec=$(date -d "$TARGET" +%s)
          start_sec=$(date -d "$START" +%s)
          now_sec=$(date -d "$NOW" +%s)

          # Hitung selisih waktu
          remaining=$((target_sec - now_sec))
          elapsed=$((now_sec - start_sec))
          total=$((target_sec - start_sec))

          # Format waktu tersisa
          days=$((remaining / 86400))
          hours=$(( (remaining % 86400) / 3600 ))
          mins=$(( (remaining % 3600) / 60 ))
          secs=$((remaining % 60))

          # Hitung persentase
          percent=$((elapsed * 100 / total))
          [ $percent -gt 100 ] && percent=100

          # Buat progress bar
          bar_len=20
          filled=$((percent * bar_len / 100))
          empty=$((bar_len - filled))
          progress_bar=$(printf '🟥%.0s' $(seq 1 $filled))$(printf '⬜%.0s' $(seq 1 $empty))

          # Buat pesan status
          if [ $percent -eq 100 ]; then
            status="🎉 WAKTUNYA TELAH TIBA! 🎉"
          elif [ $percent -gt 90 ]; then
            status="Sebentar lagi..."
          elif [ $percent -gt 50 ]; then
            status="Sudah lebih dari setengah!"
          else
            status="Masih ada waktu..."
          fi

          # Format payload Discord
          payload='{
            "embeds": [{
              "title": "⏳ COUNTDOWN BOT ⏳",
              "description": "'"$status"'",
              "color": 5814783,
              "fields": [
                {"name": "Waktu Tersisa", "value": "'"${days}d ${hours}h ${mins}m ${secs}s"'", "inline": true},
                {"name": "Progress", "value": "'"$progress_bar ${percent}%"'", "inline": false}
              ],
              "footer": {"text": "Update terakhir: '"$NOW"'"}
            }]
          }'

          # Kirim ke Discord
          curl -X POST -H "Content-Type: application/json" -d "$payload" "$WEBHOOK_URL"
